---
- hosts: caldeirao
  remote_user: root
  tasks:
    - name: "Instalação do Apache2 + PHP7"
      apt: name={{ item }} state=present
      with_items:
                - apache2
                - php7.0
                - libapache2-mod-php7.0


    - name: "Subindo o Apache2 + PHP7"
      service: name={{ item }} state=started enabled=yes
      with_items:
                - apache2
